#!/bin/sh

#15 FPS
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! ffmpegcolorspace ! videoscale ! videorate ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,framerate=15/1,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink

#20 FPS
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! ffmpegcolorspace ! videoscale ! videorate ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,framerate=20/1,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink

#NO rate conversion
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink
#crop
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! videoscale ! width=640,height=480 ! videocrop top=16 bottom=0 right=0 left=0 ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink
gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! videoscale ! video/x-raw-yuv,width=320,height=240 ! videocrop top=12 bottom=12 right=0 left=0 ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ videotestsrc ! videoscale ! video/x-raw-yuv,width=640,height=480 ! videocrop top=16 bottom=0 right=0 left=0 ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ximagesink
