#!/bin/sh

#15 FPS
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! ffmpegcolorspace ! videoscale ! videorate ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,framerate=15/1,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink

#20 FPS
gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! ffmpegcolorspace ! videoscale ! videorate ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,framerate=20/1,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink

#NO rate conversion
#gst-launch --gst-plugin-path=/home/wall/led_wall/gst/ v4l2src device=/dev/video0 ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb,width=96,height=64,format='(fourcc)'RGBA,red_mask='(int)'65280,green_mask='(int)'16711680,blue_mask='(int)'-16777216 ! deinterlace ! ledwallvideosink
